export {default as Registration} from './registration/Registration';
export {default as Home } from './home/Home';
export {default as Navbar} from './navbar/Navbar';
export {default as Body} from './body/Body';
export {default as DocFormAjout} from './docFormAjout/DocFormAjout';
export {default as DocsList} from './docsList/DocsList';
export {default as Dashboard} from './dashboard/Dashboard';
export {default as ProfilePage} from './profilePage/ProfilePage';
export {default as SettingsForm} from './settingsForm/SettingsForm';
export {default as PasswordForm} from './passwordForm/PasswordForm';
export {default as AddAdminForm} from './addAdminForm/AddAdminForm';
export {default as Configurations} from './configurations/Configurations';
export {default as Accueil } from './accueil/Accueil';
export {default as UploadPage} from './uploadPage/UploadPage';