import { createContext, useState } from "react";

const RessourcesContext = createContext({});

export const RessourcesProvider = ({ children }) => {
  const defaultData = {
    idProject: "",
    panelColor: "#000000",
    panelTextColor: "#000000",
    panelWidth: "",
    memoSection: "",
    memoBackgroundColor: "#000000",
    memoFontColor: "#000000",
    generalUrl: "",
    timer: "",
    resizeBarWidth: "",
    backgroundLanguage: "#000000",
    textColorLanguage: "#ffffff",
    fontTitleMemo: "",
    fontTextMemo: "",
    buttonMemoBgColor: "#000000",
    buttonMemoFontColor: "#000000",
    buttonMemoFontSize: "",
    arrondiMemo: "",
    sectionEmailDisplay: "",
    textMemoSize: "",
    titleMemoSize: "",
    paddingUnderTitle: "",
    traitDisplay: "",
    traitColor: "#000000",
    traitWidth: "",
    sectionBorderDisplay: "",
    sectionBorderWidth: "",
    sectionBorderColor: "#000000",
  };
  const [languages, setLanguages] = useState([]);
  const [sections, setSections] = useState([]);
  const [themeSections, setThemeSections] = useState([]);
  const [confSelected, setConfSelected] = useState(defaultData);
  const [btnClicked, setBtnClicked] = useState("users");
  const polices = [
    { title: "---", value: "" },
    { title: "Agency FB", value: "Agency FB" },
    { title: "Algerian", value: "Algerian" },
    { title: "Arial", value: "Arial" },
    { title: "Arial Black", value: "Arial Black" },
    { title: "Bahnschrift", value: "Bahnschrift" },
    { title: "Baskerville Old Face", value: "Baskerville Old Face" },
    { title: "Bauhaus 93", value: "Bauhaus 93" },
    { title: "Bell MT", value: "Bell MT" },
    { title: "Berlin Sans FB", value: "Berlin Sans FB" },
    { title: "Bernard MT Condensed", value: "Bernard MT Condensed" },
    { title: "Book Antiqua", value: "Book Antiqua" },
    { title: "Bookman Old Style", value: "Bookman Old Style" },
    { title: "Bradley Hand ITC", value: "Bradley Hand ITC" },
    { title: "Broadway", value: "Broadway" },
    { title: "Calibri", value: "Calibri" },
    { title: "Calisto MT", value: "Calisto MT" },
    { title: "Cambria", value: "Cambria" },
    { title: "Candara", value: "Candara" },
    { title: "Castellar", value: "Castellar" },
    { title: "Century", value: "Century" },
    { title: "Century Gothic", value: "Century Gothic" },
    { title: "Chiller", value: "Chiller" },
    { title: "Comic Sans MS", value: "Comic Sans MS" },
    { title: "Consolas", value: "Consolas" },
    { title: "Constantia", value: "Constantia" },
    { title: "Cooper Black", value: "Cooper Black" },
    { title: "Copperplate Gothic Bold", value: "Copperplate Gothic Bold" },
    { title: "Courier New", value: "Courier New" },
    { title: "Elephant", value: "Elephant" },
    { title: "Engravers MT", value: "Engravers MT" },
    { title: "Eras Bold ITC", value: "Eras Bold ITC" },
    { title: "Felix Titling", value: "Felix Titling" },
    { title: "Footlight MT Light", value: "Footlight MT Light" },
    { title: "Franklin Gothic Medium", value: "Franklin Gothic Medium" },
    { title: "Freestyle Script", value: "Freestyle Script" },
    { title: "French Script MT", value: "French Script MT" },
    { title: "Gabriola", value: "Gabriola" },
    { title: "Garamond", value: "Garamond" },
    { title: "Georgia", value: "Georgia" },
    { title: "Gigi", value: "Gigi" },
    { title: "Gill Sans MT", value: "Gill Sans MT" },
    { title: "Goudy Old Style", value: "Goudy Old Style" },
    { title: "Haettenschweiler", value: "Haettenschweiler" },
    { title: "Harlow Solid Italic", value: "Harlow Solid Italic" },
    { title: "Harrington", value: "Harrington" },
    { title: "High Tower Text", value: "High Tower Text" },
    { title: "Impact", value: "Impact" },
    { title: "Imprint MT Shadow", value: "Imprint MT Shadow" },
    { title: "Informal Roman", value: "Informal Roman" },
    { title: "Ink Free", value: "Ink Free" },
    { title: "Jokerman", value: "Jokerman" },
    { title: "Kristen ITC", value: "Kristen ITC" },
    { title: "Lucida Bright", value: "Lucida Bright" },
    { title: "Lucida Calligraphy", value: "Lucida Calligraphy" },
    { title: "Lucida Console", value: "Lucida Console" },
    { title: "Lucida Handwriting", value: "Lucida Handwriting" },
    { title: "Lucida Sans Unicode", value: "Lucida Sans Unicode" },
    { title: "Magneto", value: "Magneto" },
    { title: "Maiandra GD", value: "Maiandra GD" },
    { title: "Malgun Gothic", value: "Malgun Gothic" },
    { title: "Matura MT Script Capitals", value: "Matura MT Script Capitals" },
    { title: "Microsoft Himalaya", value: "Microsoft Himalaya" },
    { title: "Microsoft JhengHei", value: "Microsoft JhengHei" },
    { title: "Microsoft New Tai Lue", value: "Microsoft New Tai Lue" },
    { title: "Microsoft PhagsPa", value: "Microsoft PhagsPa" },
    { title: "Microsoft Sans Serif", value: "Microsoft Sans Serif" },
    { title: "Microsoft Tai Le", value: "Microsoft Tai Le" },
    { title: "Microsoft YaHei", value: "Microsoft YaHei" },
    { title: "Microsoft Yi Baiti", value: "Microsoft Yi Baiti" },
    { title: "Mistral", value: "Mistral" },
    { title: "Modern No. 20", value: "Modern No. 20" },
    { title: "Mongolian Baiti", value: "Mongolian Baiti" },
    { title: "Monotype Corsiva", value: "Monotype Corsiva" },
    { title: "MS Gothic", value: "MS Gothic" },
    { title: "MS PGothic", value: "MS PGothic" },
    { title: "MS UI Gothic", value: "MS UI Gothic" },
    { title: "MV Boli", value: "MV Boli" },
    { title: "Myanmar Text", value: "Myanmar Text" },
    { title: "Niagara Engraved", value: "Niagara Engraved" },
    { title: "Niagara Solid", value: "Niagara Solid" },
    { title: "OCR A Extended", value: "OCR A Extended" },
    { title: "Old English Text MT", value: "Old English Text MT" },
    { title: "Palatino Linotype", value: "Palatino Linotype" },
    { title: "Papyrus", value: "Papyrus" },
    { title: "Perpetua", value: "Perpetua" },
    { title: "Playbill", value: "Playbill" },
    { title: "Poor Richard", value: "Poor Richard" },
    { title: "Ravie", value: "Ravie" },
    { title: "Rockwell", value: "Rockwell" },
    { title: "Segoe Print", value: "Segoe Print" },
    { title: "Segoe Script", value: "Segoe Script" },
    { title: "Segoe UI", value: "Segoe UI" },
    { title: "Showcard Gothic", value: "Showcard Gothic" },
    { title: "Sitka Text", value: "Sitka Text" },
    { title: "Snap ITC", value: "Snap ITC" },
    { title: "Stencil", value: "Stencil" },
    { title: "Sylfaen", value: "Sylfaen" },
    { title: "Symbol", value: "Symbol" },
    { title: "Tahoma", value: "Tahoma" },
    { title: "Tempus Sans ITC", value: "Tempus Sans ITC" },
    { title: "Times New Roman", value: "Times New Roman" },
    { title: "Trebuchet MS", value: "Trebuchet MS" },
    { title: "Tw Cen MT", value: "Tw Cen MT" },
    { title: "Verdana", value: "Verdana" },
    { title: "Viner Hand ITC", value: "Viner Hand ITC" },
    { title: "Vivaldi", value: "Vivaldi" },
    { title: "Vladimir Script", value: "Vladimir Script" },
    { title: "Webdings", value: "Webdings" },
    { title: "Wingdings", value: "Wingdings" },
    { title: "Yu Gothic", value: "Yu Gothic" }
  ];
  
  return (
    <RessourcesContext.Provider
      value={{
        languages,
        setLanguages,
        confSelected,
        setConfSelected,
        sections,
        setSections,
        themeSections,
        setThemeSections,
        btnClicked,
        setBtnClicked,
        polices,
      }}
    >
      {children}
    </RessourcesContext.Provider>
  );
};

export default RessourcesContext;
